/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InterestingRoute } from './routes/interesting'
import { Route as BooksRoute } from './routes/books'
import { Route as AboutRoute } from './routes/about'
import { Route as IndexRoute } from './routes/index'
import { Route as AboutUserManualRoute } from './routes/about.user-manual'
import { Route as AboutHowIGotIntoPmRoute } from './routes/about.how-i-got-into-pm'

// Create/Update Routes

const InterestingRouteWithChildren = InterestingRoute._addFileChildren([])
const BooksRouteWithChildren = BooksRoute._addFileChildren([])
const AboutRouteWithChildren = AboutRoute._addFileChildren([
  AboutUserManualRoute,
  AboutHowIGotIntoPmRoute,
])
const IndexRouteWithChildren = IndexRoute._addFileChildren([])

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/interesting': {
      id: '/interesting'
      path: '/interesting'
      fullPath: '/interesting'
      preLoaderRoute: typeof InterestingRouteWithChildren
      parentRoute: typeof rootRoute
    }
    '/about/how-i-got-into-pm': {
      id: '/about/how-i-got-into-pm'
      path: '/how-i-got-into-pm'
      fullPath: '/about/how-i-got-into-pm'
      preLoaderRoute: typeof AboutHowIGotIntoPmRouteWithChildren
      parentRoute: typeof AboutRouteWithChildren
    }
    '/about/user-manual': {
      id: '/about/user-manual'
      path: '/user-manual'
      fullPath: '/about/user-manual'
      preLoaderRoute: typeof AboutUserManualRouteWithChildren
      parentRoute: typeof AboutRouteWithChildren
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  AboutRouteWithChildren,
  BooksRouteWithChildren,
  InterestingRouteWithChildren,
])

/* prettier-ignore-end */