name: Update Goodreads database every 4 days

on:
  schedule:
    - cron: "19 19 */4 * *"

  workflow_dispatch:

jobs:
  update_goodreads_db:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update Goodreads database
        env:
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
          GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
        run: |
          # Initialize database (creates if doesn't exist)
          npm run db:init
          # Check and sync each shelf individually for better accuracy
          npm run check:shelf to-read
          npm run check:shelf read
          npm run check:shelf currently-reading

      - name: Commit updated database
        run: |
          echo "📊 Checking database file status..."
          ls -la public/books.db
          echo "📊 Git status before add:"
          git status --porcelain
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/books.db
          echo "📊 Git status after add:"
          git status --porcelain
          echo "📊 Git diff staged:"
          git diff --staged --stat
          if git diff --staged --quiet; then
            echo "📊 No changes detected in database file"
          else
            echo "📊 Changes detected, creating commit..."
            git commit -m "📚 Update Goodreads database - $(date -u '+%Y-%m-%d %H:%M UTC')
            
            🤖 Generated with [Claude Code](https://claude.ai/code)
            
            Co-Authored-By: Claude <noreply@anthropic.com>"
            echo "📊 Pushing changes to repository..."
            git push
          fi
